/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
extern "C" {
    pub fn add(x: ::std::os::raw::c_int, y: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn upcase(c: ::std::os::raw::c_char) -> ::std::os::raw::c_uchar;
}
